name: Build IG and Deploy to GitHub Pages

on:
  push:
    branches-ignore:
      - 'gh-pages'
  pull_request:
  workflow_dispatch:

jobs:
  build-and-deploy:
    permissions:
      contents: write
      pull-requests: write
    uses: WorldHealthOrganization/smart-base/.github/workflows/ghbuild.yml@main
    with:
      do_dak: false
      deploy: true
